# Jekyll settings
#
title: Brève histoire du verger-école de l'AALE
email: webmestre@arboriculteurs-lichtenberg.eu
lang: fr-FR
description: 
  Le verger-école : brève histoire, du défrichage aux premières animations scolaires.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arboriculteurs-lichtenberg.eu/verger-ecole" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll
nav_direction: vertical # vertical, horizontal 
image_dir: "assets/images"
sound_dir: "assets/sounds"
collections:
    - sections
# Build settings
markdown: kramdown
plugins:
  - github-pages
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
include:
  - assets
